language: python

dist: xenial

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

sudo: false

env:
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=2.2
    - DJANGO=3.0

matrix:
    fast_finish: true
    include:
      - { python: "3.5", env: DJANGO=1.11 }
      - { python: "3.5", env: DJANGO=2.0 }
      - { python: "3.5", env: DJANGO=2.1 }
      - { python: "3.5", env: DJANGO=2.2 }

      - { python: "3.6", env: DJANGO=1.11 }
      - { python: "3.6", env: DJANGO=2.0 }
      - { python: "3.6", env: DJANGO=2.1 }
      - { python: "3.6", env: DJANGO=2.2 }
      - { python: "3.6", env: DJANGO=3.0 }
      - { python: "3.6", env: DJANGO=master }

      - { python: "3.7", env: DJANGO=1.11 }
      - { python: "3.7", env: DJANGO=2.0 }
      - { python: "3.7", env: DJANGO=2.1 }
      - { python: "3.7", env: DJANGO=2.2 }
      - { python: "3.7", env: DJANGO=3.0 }
      - { python: "3.7", env: DJANGO=master }

      - { python: "3.8", env: DJANGO=2.2 }
      - { python: "3.8", env: DJANGO=3.0 }
      - { python: "3.8", env: DJANGO=master }

    allow_failures:
      - env: DJANGO=master
      
install:
    - pip install tox tox-venv tox-travis

script:
    - tox

notifications:
    email: false